In [1]:
import numpy as np
from sklearn.datasets import make_classification

In [10]:
X,y = make_classification(n_samples=100,n_classes=2)

In [11]:
X.shape

(100, 20)

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [55]:
class Perceptron():
    
    def predict(self,X):
        z = X@self.w
        return np.where(z>=0,1,0)
    
    def fit(self,X,y,lr=0.001,epochs=100):
        self.w_all = []
        self.errors_all = []
        
        for _ in range(epochs):
            self.w = np.zeros(X.shape[-1])
            error = 0
            for xi,target in zip(X,y):
                error = np.maximum(0,-1*target*self.predict(xi))
                self.w += lr*(target - self.predict(xi))*xi 
                
                self.w_all.append(self.w)
                self.errors_all.append(error)
        return self.w_all,self.errors_all
    
    def confusion_matrix(self,y_test,y_pred):
        n  = len(np.unique(y_test))
        
        confusion_matrix = np.zeros((n,n))
        
        for t,p in zip(y_test,y_pred):
            confusion_matrix[t,p] += 1
            
        return confusion_matrix

In [56]:
perceptron = Perceptron()

In [57]:
weights,error = perceptron.fit(X_train,y_train)

In [58]:
perceptron.predict(X_test)

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0])

In [59]:
y_test

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [60]:
perceptron.confusion_matrix(y_test,perceptron.predict(X_test))

array([[10.,  2.],
       [ 2.,  6.]])