# Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display,Math,Latex
import seaborn as sns

# One Hot Encoder

In [41]:
class LabelTransformer(object):

  def __init__(self,n_classes:int = None):
    self.n_classes= n_classes

  @property
  def n_classes(self):
    return self.__n_classes

  @n_classes.setter
  def n_classes(self,K):
    self.__n_classes = K
    self.__encoder = None if K is None else np.eye(K)

  @property
  def encoder(self):
    return self.__encoder

  def encode(self,class_indices:np.ndarray):
    if self.n_classes == None:
      self.n_classes = np.max(class_indices) + 1
    return self.encoder[class_indices]


  def decode(self,onehoe:np.ndarray):
    return np.argmax(onehot,axis = 1)


# Class for One Hot Encoding 
**By Shubham Harkare**

In [3]:
class OneHotEncoder():
    def encode(self,X:np.ndarray)->np.ndarray:
        encoder = np.zeros((X.shape[0],np.unique(X).shape[0]))
        encoder[np.arange(encoder.shape[0]),X] = 1
        return encoder
    
    def decode(self,onehot:np.ndarray)->np.ndarray:
        return np.argmax(onehot,axis = 1)

In [4]:
X = np.array([0,1,3,2])

(array([0, 1, 2, 3]), array([0, 1, 3, 2]))

In [29]:
onehotenc = OneHotEncoder()

In [30]:
ohc = onehotenc.encode(X)

In [31]:
ohc

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [32]:
onehotenc.decode(ohc)

array([0, 1, 3, 2], dtype=int64)

In [23]:
np.arange(X.shape[0])

array([0, 1, 2, 3])

In [42]:
binary_labels = LabelTransformer(2).encode(np.array([1,0,1,0]))
binary_labels

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

## Least square classification implementation

### **Training**

1. We have ${X}$ of shape ${(n,m)}$ where **${n}$** is the number of rows and **${m}$** the number of features 

2. We have ${Y}$ of shape ${(n,k)}$ where **${n}$** is the number of rows and **${k}$** the number of lables

### Model

$${Y_{n,k} = X_{n,m+1}W_{m+1,k}}$$

### Loss Function

$$ J(W) = (1/2)(XW-Y)^{T}(XW-Y)$$

# Loss Function Class
**Shubham Harkare**

In [34]:
class LeastSquareClassifier():
    
    def __init__(self):
        self.t0 = 20
        self.t1 = 100
        
    def predict(self,X:np.ndarray) -> np.ndarray:
        assert X.shape[-1] == self.w.shape[0], f'{X.shape} and {w.shape} are not compatible'
        return np.argmax(X @ self.w,axis=1)
    
    def predict_internal(self,X:np.ndarray) -> np.ndarray:
        assert X.shape[-1] == self.w.shape[0], f'{X.shape} and {w.shape} are not compatible'
        return X @ self.w
    
    def loss(self,X:np.ndarray,y:np.ndarray) -> float:
        e = self.predict_internal(X) - y
        return (1/2)*(np.transpose(e) @ e)
    
    def fit(self,X:np.ndarray,y:np.ndarray) -> np.ndarray:
        self.w = np.linalg.inv(np.transpose(X)@X)@np.transpose(X)@y
        return self.w
        
    
    

In [46]:
lsc = LeastSquareClassifier()
X = np.array([[1,-3,2,-5],[1,9,-4,7]])
w = np.array([1,1,1,1])
y = np.array([1,0])

In [57]:
lsc.w = w
lsc.predict_internal(X)

array([-5, 13])

In [58]:
lsc.loss(X,y)

102.5

## Confusion Matrix ##

In [5]:
def confusion_matrix(y_test,y_pred):
  tp = np.where((y_test == 1) and (y_pred == 1),1,0).sum()
  tn = np.where((y_test == 0) and (y_pred == 0),1,0).sum()
  fp = np.where((y_test == 0) and (y_pred == 1),1,0).sum()
  fn = np.where((y_test == 1) and (y_pred == 0),1,0).sum()

  return np.array([
                   [tp,fp],
                   [fn,tn]

  ])

# Perceptron Algorithm

## Training data

1. Feature Matrix : ${X_{n,m+1}}$ includes the dummy feature ${x_0}$ which is set to 1
2. Label vector: ${y_{n,1}}$


Perceptron can only solve **binary classification** 

## Model

$${h(w): y = sign(w^{T}phi(x)) }$$

# Polynomial Transformation

# Perceptron class

In [7]:
class Perceptron:
  '''
  It uses the following class variables:
  w: To store the weight vectors
  w_all : To store all the weight vectors
  errors_all : To store all the error values
  '''

  def __init__(self):
    return 
  
  def predict(self,X:np.ndarray):
    z = X @ self.w
    return np.where(z>=0,1,-1)

  def loss(self,X,y):
    return np.sum(np.maximum(-1*self.predict(X)*y,np.zeros(y.shape[0])))

  def train(self,X,y,epochs=10,lr=0.001):
    self.w = np.zeros(X.shape[-1])
    self.errors_all = []
    self.w_all = []

    for _ in range(epochs):
      errors = 0
      for x,target in zip(X,y):
        self.w +=  lr * (target - self.predict(Xi))*xi
        errors +=  (max(-1*self.predict(x)*target,0))

      self.errors_all.append(errors)
      self.w_all.append(self.w)
      print("w: ",self.w) 
      print("J(w): ",self.errors_all[-1] )




# perceptron 
**Shubham Harkare**

In [96]:
class Perceptron:
    def __init__(self):
        return
    
    def predict(self,X:np.ndarray)->np.ndarray:
        z = X @ self.w
        return np.where(z>=0,1,-1)
    def loss(self,X:np.ndarray,y:np.ndarray)->float:
        return np.sum(np.maximum(-1*self.predict(X)*y,
                                np.zeros(X.shape[0])))
    
    def train(self,X:np.ndarray,y:np.ndarray,epoch=10,lr=0.001):
        self.w = np.zeros(X.shape[-1])
        self.errors_all = []
        self.w_all = []
        for _ in range(epoch):
            errors = 0
            for xi,target in zip(X,y):
                
                self.w += lr*(target - self.predict(xi))*xi
                errors += max(0,-1*target*self.predict(xi))
                
            self.errors_all.append(errors)
            self.w_all.append(self.w)
            print("w : ",perceptron_obj.w)
            print("J(w) :",perceptron_obj.errors_all[-1])
        

In [97]:
perceptron_obj = Perceptron()

In [98]:
X = np.array([[1,3,5,4],[2,4,-0.7,-1.3]])

In [99]:
perceptron_obj.w = np.array([1,1,1,1])

In [100]:
perceptron_obj.predict(X)

array([1, 1])

In [101]:
y = np.array([0,0])

In [102]:
perceptron_obj.train(X,y)

w :  [ 0.001   0.001  -0.0057 -0.0053]
J(w) : 0
w :  [ 0.00000000e+00  0.00000000e+00 -1.08420217e-19  2.16840434e-19]
J(w) : 0
w :  [ 0.001   0.001  -0.0057 -0.0053]
J(w) : 0
w :  [ 0.00000000e+00  0.00000000e+00 -1.08420217e-19  2.16840434e-19]
J(w) : 0
w :  [ 0.001   0.001  -0.0057 -0.0053]
J(w) : 0
w :  [ 0.00000000e+00  0.00000000e+00 -1.08420217e-19  2.16840434e-19]
J(w) : 0
w :  [ 0.001   0.001  -0.0057 -0.0053]
J(w) : 0
w :  [ 0.00000000e+00  0.00000000e+00 -1.08420217e-19  2.16840434e-19]
J(w) : 0
w :  [ 0.001   0.001  -0.0057 -0.0053]
J(w) : 0
w :  [ 0.00000000e+00  0.00000000e+00 -1.08420217e-19  2.16840434e-19]
J(w) : 0


In [103]:
from sklearn.datasets import make_classification
X,y = make_classification()

In [104]:
perceptron_obj.train(X,y)

w :  [ 0.00562385  0.00275384 -0.00143494  0.00510794 -0.00119139 -0.00470875
  0.00068081 -0.00268376 -0.009079   -0.00329655 -0.00096673 -0.00241762
  0.00822122 -0.0037898   0.00611837 -0.00124686 -0.00118837  0.00206481
  0.00546445 -0.01567961]
J(w) : 0
w :  [ 0.00207865 -0.00295641  0.00201695  0.00163579  0.00256535 -0.00129913
 -0.00023451 -0.00421661 -0.00385787 -0.00147948  0.00294445 -0.0030916
  0.00515173 -0.0067153   0.00027119  0.00036816 -0.00706993 -0.00080221
  0.00073647 -0.01356825]
J(w) : 1
w :  [ 0.00080712  0.00144621 -0.00096963  0.00783672  0.00205545 -0.0033677
 -0.00073977 -0.00049221 -0.00691583  0.00093351 -0.00248106 -0.0079437
  0.00594751 -0.00284356  0.00793388 -0.00362545  0.0006234   0.00331061
  0.00426556 -0.01099493]
J(w) : 1
w :  [-0.00309357  0.00345537 -0.00197242  0.00685588 -0.00075137 -0.0040053
 -0.00984813  0.0002015  -0.00486454  0.00157907 -0.00618308  0.00186878
  0.00609452 -0.00145695  0.00302629 -0.00075501 -0.00297737 -0.00455749
 -0

3